name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11', '17', '20']
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build
      run: mvn package

    - name: Integration Test
      run: mvn verify
